- name: connection check
  hosts: all
  become: yes


  
  tasks:
    - name: check
      ping:

- name: ensure have all dependencies
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.apt: name=nginx state=latest
    - name: set settings
      service: name=nginx state=started enabled=yes
